apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: etcd-client-cert
  namespace: monitoring
spec:
  itemPath: "vaults/kubernetes/items/etcd-client-cert"
---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-client-cert
  namespace: monitoring
type: Opaque
data: {}  # The 1Password Operator will populate this
