
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: capacitor
  namespace: flux-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`capacitor.k8s.kuipr.de`)
      kind: Rule
      services:
        - name: capacitor
          port: 9000
