apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  
  values:
    # Service monitor for Prometheus scraping
    serviceMonitor:
      enabled: true

    # Ingress configuration - disabled, using IngressRoute
    ingress:
      enabled: false

    # Admin user configuration
    admin:
      existingSecret: "default-grafana-user-secret"
      userKey: username
      passwordKey: password

    # Grafana plugins
    plugins: []

    # Datasource configuration
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://kube-prometheus-stack-prometheus:9090
            access: proxy
            isDefault: true
            jsonData:
              timeInterval: 30s

    # Dashboard providers
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default

    # Pre-installed dashboards
    dashboards:
      default:
        # Kubernetes cluster monitoring dashboard
        kubernetes-cluster-monitoring:
          gnetId: 7249
          revision: 1
          datasource: Prometheus
        
        # Node exporter dashboard
        node-exporter:
          gnetId: 1860
          revision: 37
          datasource: Prometheus
        
        # Flux monitoring dashboard
        flux-cluster:
          gnetId: 16714
          revision: 1
          datasource: Prometheus

    # Resource configuration
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # Persistence
    persistence:
      enabled: true
      storageClassName: longhorn
      accessModes:
        - ReadWriteOnce
      size: 1Gi
