apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: 8.14.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: monitoring
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ## https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml

    serviceMonitor:
      ## If true, a ServiceMonitor CR is created for a prometheus operator
      ## https://github.com/coreos/prometheus-operator
      ##
      enabled: true

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls.certresolver: labca

    admin:
      existingSecret: "default-grafana-user-secret"
      userKey: username
      passwordKey: password

    plugins:
      []
      # - digrich-bubblechart-panel
      # - grafana-clock-panel
      ## You can also use other plugin download URL, as long as they are valid zip files,
      ## and specify the name of the plugin after the semicolon. Like this:
      # - https://grafana.com/api/plugins/marcusolsson-json-datasource/versions/1.3.2/download;marcusolsson-json-datasource

    ## Configure grafana datasources
    ## ref: http://docs.grafana.org/administration/provisioning/#datasources
    ##

    datasources: {}
    #  datasources.yaml:
    #    apiVersion: 1
    #    datasources:
    #    - name: Prometheus
    #      type: prometheus
    #      url: http://prometheus-prometheus-server
    #      access: proxy
    #      isDefault: true
    #    - name: CloudWatch
    #      type: cloudwatch
    #      access: proxy
    #      uid: cloudwatch
    #      editable: false
    #      jsonData:
    #        authType: default
    #        defaultRegion: us-east-1
    #    deleteDatasources: []
    #    - name: Prometheus
