apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - repo.yaml
  - prom-deployment.yaml
  - grafana-deployment.yaml

configMapGenerator:
  - name: flux-kube-state-metrics
    files:
      - kube-state-metrics.yaml=flux-kube-state-metrics_configmap.yaml

configurations:
  - kustomizeconfig.yaml

# Ensure proper ordering
generatorOptions:
  disableNameSuffixHash: true
