apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - repo.yaml
  - prom-deployment.yaml
  - grafana-deployment.yaml
  - namespace.yaml
configMapGenerator:
  - name: flux-kube-state-metrics
    files:
      - flux-kube-state-metrics_configmap.yaml
configurations:
  - kustomizeconfig.yaml
