apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-charts
  namespace: monitoring
spec:
  interval: 2h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-charts
  namespace: monitoring
spec:
  interval: 2h
  url: https://grafana.github.io/helm-charts
