apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wazuh
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: wazuh
  chart:
    spec:
      chart: wazuh
      sourceRef:
        kind: HelmRepository
        name: wazuh
        namespace: flux-system
      version: "4.11.0"
  values:
    # Longhorn storage configuration
    storageClassName: longhorn
    
    # Manager configuration
    manager:
      replicaCount: 1
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1Gi
      persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi
    
    # Indexer configuration
    indexer:
      replicaCount: 1
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
      persistence:
        enabled: true
        storageClass: longhorn
        size: 20Gi
    
    # Dashboard configuration
    dashboard:
      enabled: true
      ingress:
        enabled: false  # We'll use Traefik IngressRoute instead
