---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: 1.9.0
  interval: 1m0s
  values:
    persistence:
      defaultClassReplicaCount: 1
    defaultSettings:
      defaultReplicaCount: 1
    service:
      ui:
        type: ClusterIP
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
          traefik.ingress.kubernetes.io/router.rule: Host(`longhorn.k8s.kuipr.de`)
