#ENC[AES256_GCM,data:/QtyhFSQpulbs8dNt0h+5T/jrRlnlShavmH5fmdbK3EmX04RcgUWhY4wBRGb,iv:cn4lpG1REWVH1UR9TU1n0SjFqXuoO3uJCXg+k76/BeA=,tag:hVMArn8HMSpTleLPb9DBXQ==,type:comment]
#ENC[AES256_GCM,data:QyhK14bWqW33V4YKcyyoTE9WzuDWxY/8fC/UqLSm0k0JyNwQCXI3u4x7sHjO,iv:10/3IMyy4HiuFwbnouA7iZHYvr2uZrQXoIV2Zp1AY58=,tag:83hZhSmhgW/VTJezJITBSg==,type:comment]
#ENC[AES256_GCM,data:jp2PiQIpZpTRlNS39PnbERUhnUUHW1cjjcYb4kqxbnT2cVp3jKkm3dk5P+Fc,iv:qSF6sNgrYEORGVT8/UuAt2HPZn36WgqGIEzYG3oe+sE=,tag:n0/if599tg5Gr5KzD5ErhQ==,type:comment]
#ENC[AES256_GCM,data:QyhK14bWqW33V4YKcyyoTE9WzuDWxY/8fC/UqLSm0k0JyNwQCXI3u4x7sHjO,iv:10/3IMyy4HiuFwbnouA7iZHYvr2uZrQXoIV2Zp1AY58=,tag:83hZhSmhgW/VTJezJITBSg==,type:comment]
#ENC[AES256_GCM,data:/QtyhFSQpulbs8dNt0h+5T/jrRlnlShavmH5fmdbK3EmX04RcgUWhY4wBRGb,iv:cn4lpG1REWVH1UR9TU1n0SjFqXuoO3uJCXg+k76/BeA=,tag:hVMArn8HMSpTleLPb9DBXQ==,type:comment]
server:
    address: ENC[AES256_GCM,data:yrfA4k8pxsLMaSLGvSGcNwWt,iv:5F+W4XOJmvFS1Ym9vCi3hNl8ZXn5VMoEamVz1/GRBBY=,tag:ILw7q9WbMaepNsYv7k/wMA==,type:str]
    endpoints:
        authz:
            auth-request:
                implementation: ENC[AES256_GCM,data:QXcXuPSsb/sSsbU=,iv:9qekh3Qb09vqnkoGvFbQ/aWWC0EVkZOdUiob0rfik7w=,tag:UhIHlK2wVBOB523wZ31h2Q==,type:str]
            forward-auth:
                implementation: ENC[AES256_GCM,data:GUhMGNkn2fApfuo=,iv:4CZusJ2TUAM5kKOm/aIX78Bu5IRkBJFwya6BaYDkRmY=,tag:FkeHRb8SvVPTbl26RDI4Dg==,type:str]
totp:
    issuer: ENC[AES256_GCM,data:+ND35wgmxiQ=,iv:kKVJlCDsNItwNuE07Rl1VuOU910aeWZ+rsvOlO1HoIU=,tag:nAtjN0j7e/owQiZkgQFQLw==,type:str]
    period: ENC[AES256_GCM,data:Jt0=,iv:WXIHdfTQfTeU99U5kC2Vo2+THAyTU9XerX6jsXMPavg=,tag:SuyIsIR2gvVT2MkXxlHwfw==,type:int]
    skew: ENC[AES256_GCM,data:zQ==,iv:/VFWTrssAhA4lzZ438s1X7a0LjbszrosvRKRdjMaRMY=,tag:vVcGR0aUpJfiBGqVgXru4Q==,type:int]
notifier:
    disable_startup_check: ENC[AES256_GCM,data:zjSbtg==,iv:J7z91hXE+p795h6Sheq3iQcJxr6ZxFCPy6EWIRE5/Rc=,tag:bDwLWF+4HtlgjJaeCcEsIA==,type:bool]
    smtp:
        address: ENC[AES256_GCM,data:V3KOsyWffCdVx0ehpdDqJKdkkNmxoF2N48rMJphSgw==,iv:z9ZslpKRhyWPwXTI3VE/LwuXPBpdjq2LXdKOjwdqIk0=,tag:1cJjeYJFMFgivH6YhkEW4A==,type:str]
        username: ENC[AES256_GCM,data:xD1nVJWY2AV28gEYLNqzU9iYKoHw375T,iv:4Hj+5q7pXD2UZVI1d2oJiXwbxJpf9b7PZr1VnoWG9zg=,tag:yPaAyqBkM3lV3ZtQcJqCfg==,type:str]
        password: ENC[AES256_GCM,data:8FlscFu9LR4q7+Swd01MzOmvEw==,iv:yD+72Gj9CEKTKS1w+pCYU2OGzOoNDgb14ZMYTVIfSr8=,tag:IQ0YiPBMdHIDbxJ1qmpLEw==,type:str]
        sender: ENC[AES256_GCM,data:uS8vuaNVyLYgTMCAtH8=,iv:Gp/9EkplmQtCYy59+kcPAKTAi7Y3tANrXESlmO395mg=,tag:LhnF99s0oandFDLqhPg2NA==,type:str]
authentication_backend:
    file:
        path: ENC[AES256_GCM,data:fgkNaRkX1ukXqXmJvKmE5Q2xTNYDdYSqHFjW,iv:rqlts6kzEHfdpDNL1ll0TZPwdBPVSzjvv5LQKoFE8GE=,tag:VGNcJ1wJGrgo/d0qKhE6Og==,type:str]
        password:
            algorithm: ENC[AES256_GCM,data:L5d6qUR6PcA=,iv:PlHSYueMCjrY2eDRiwuAoqwh+1lnnIl5MTbbvqko1+o=,tag:/eJmRnzgjuVPl5V2R6rn/Q==,type:str]
            iterations: ENC[AES256_GCM,data:/w==,iv:dJZYA3reWZSo5CDqflMrcvrFVfO5k1pbScNtgwiJ2lQ=,tag:fPYCE6B0i8Loik0JO+CkSg==,type:int]
            salt_length: ENC[AES256_GCM,data:5+Y=,iv:v55L/RTO1Ws49q86ZGa8w9oGWkzlRgNLTRMI6ffJ80A=,tag:qB9GcJEJB3wykEbm0m186Q==,type:int]
            parallelism: ENC[AES256_GCM,data:sg==,iv:RqJdPQMK8S4S7omtJ0+YDws8PiJOl3ePWDpCSf/IP+8=,tag:fOvdwuvDTjM09KRssuQ7Gg==,type:int]
            memory: ENC[AES256_GCM,data:ONw=,iv:jgzEj8hP0bFnoK5vL3gw5qzI+UJ7tT27h2QId4RV15s=,tag:BGb6YlUuKobPK5hqFf+OTw==,type:int]
identity_validation:
    reset_password:
        jwt_secret: ENC[AES256_GCM,data:+R6VOeG4WwldWOwzmdgXszEss/SVncNlBOn2VsZM+iGs7Twtp1psQiJCwlov8/I5YeqBg5r7gI3oNBMgLvlNBQ==,iv:nHwGOmxFOxjto28IAmn1nUOLnwciIXESqffbAl2Uli8=,tag:BycjjeQYXC9p2NtQmgDZ9w==,type:str]
access_control:
    default_policy: ENC[AES256_GCM,data:BeDquffMXnjrpQ==,iv:IVvjEk8GBVKm32gTAoTyHgjVmWAxRYTgksXIG+1Kfuw=,tag:y7j3Wqzd16Yn9+79nqvd4A==,type:str]
    rules:
        - domain: ENC[AES256_GCM,data:qmr2Bc1eJ3igjg==,iv:WvpLUyRGKq5UBix07uoZtJBgmnfSXFrjdIzkONqZLcI=,tag:aI9/kdkOajQxKbH7xvMj6w==,type:str]
          resources:
            - ENC[AES256_GCM,data:xBBiw9t5O2XZ,iv:AoX953M+Pjp+hJjkXtrE9z3qJkxRYhQnyR7BeVl/dNY=,tag:9RSP96IPk02QB4Jb6mAcMQ==,type:str]
            - ENC[AES256_GCM,data:ILYbMgaQZdv1YkhfaQ==,iv:ycLLNjQG8iH2hkEArv1QubmWkALV9O/t46NY7GVPVW8=,tag:P0eCg6ilu1KPggQKLfOBfg==,type:str]
          policy: ENC[AES256_GCM,data:+0q5M2DC,iv:klYh1oMvzPEqszQL79d0LqwbSN5Abs+SKo71V75ZJNs=,tag:SzZBNGuWR4IM2p2hmUy38Q==,type:str]
session:
    secret: ENC[AES256_GCM,data:uNhnMt84oqH5yhDkdEVJ0GW1sS3ueH8m6hmXgX0gJzPQ+85t32Te1yTLZIUALqEGdLammUIy6AeWEmsPR540uw==,iv:MjLFH8TypcuGb8EGbTITAdJz6b6SOYf3gTa2CQUslhM=,tag:ss9sVuGv7HAmnp40Cq1gtA==,type:str]
    name: ENC[AES256_GCM,data:LHZ+wu2xAbqvyWpi15UrQA==,iv:KCYH4S73sz9KqpFGl/XUwfyuvtbutHbgnhMoK6uTD5Y=,tag:BQ2yFt10WDX3n/FP3dgvwg==,type:str]
    same_site: ENC[AES256_GCM,data:RVFA,iv:Xj7EeNPEvYAHHM7EbFx+2qOhTkAL6ocNn3rcU0lfO38=,tag:cUpX/OOyIH4SKGHh5OTx6w==,type:str]
    inactivity: ENC[AES256_GCM,data:yjw=,iv:nT8fpmDA/SOvbVUz9znaYx5Y2iM4zC60KxP2/tZu3z0=,tag:ceqNOvhz8hBYhjAVfJg54A==,type:str]
    expiration: ENC[AES256_GCM,data:HxRO,iv:qQucozMj1c+wioturAq3fMjRQCt5KSH9LkIzpIjLwE8=,tag:C9mH2wqut+GCUSUjchvkBw==,type:str]
    remember_me: ENC[AES256_GCM,data:d6g=,iv:nJ1nlN9n/3RXjLWM9bPOgp6Z8zbiRGBBCBiYV9YrRrg=,tag:UYXf9aPMlcS/7p8YSkHjfQ==,type:str]
    cookies:
        - domain: ENC[AES256_GCM,data:uhNknpNsDAM=,iv:NuzXLcbFOygf0MGD8c1+J52V/+2oPUof5M8hVq5tEQI=,tag:GytEapnFkix0QOq0GCtQTw==,type:str]
          authelia_url: ENC[AES256_GCM,data:PnXIW1icasPNmZX9PwX9PHX8Qa7vaP2v2A==,iv:1sRpV0VdNKw4F0h5TMLO+0A/bIQL5/L/ArjjM4Af6yg=,tag:Z9hALZVXWP67t3I5wZuAtQ==,type:str]
          default_redirection_url: ENC[AES256_GCM,data:Pc5C0+9o7+Cpkzik3HtVtgxOVLjdHqhL094=,iv:HM7yff3rm5ABAa0wL21ZFPH9n2Nsi2oO4kVxGRA+bKU=,tag:NEvuJo7iOk/y7H1FVCb3eA==,type:str]
          name: ENC[AES256_GCM,data:Cm0AUJ8L+iJ8z1wuHT5+Ng==,iv:W7Iqd5pXith1GyD/3e2F7JkORkyBKtMDA7/JFb2o7No=,tag:FtZB540+JFeqPVAAnzT/OA==,type:str]
          same_site: ENC[AES256_GCM,data:8YVA,iv:REYbsYAd14/Ao80cW5oiA9+3eXkoqx6MEH9BRWMkgfs=,tag:S92VWAdtyp1U6pQuXg5pEQ==,type:str]
          inactivity: ENC[AES256_GCM,data:sy4=,iv:vdi3T2EmZL07HQ4pLWByywdC1lKdnn+darj2+xl2FnQ=,tag:RmHfMun71+L56QCpl+LBAg==,type:str]
          expiration: ENC[AES256_GCM,data:6M3e,iv:fkE7N1dJZYuRFIU9WhkyEHsD03uGtvdtkk33g21Cx9w=,tag:FfkAO83WKEwNm2m6jVSCLw==,type:str]
          remember_me: ENC[AES256_GCM,data:jvQ=,iv:nldMDougDbZeCfQNtijnWFnJBoPYDuSZk0qBkqdG/cw=,tag:6qZm8HmcRLaRw2sbxpDL8w==,type:str]
storage:
    encryption_key: ENC[AES256_GCM,data:Q1Y+VUwqJGdI1EZWYLFcChU1BiF/FzuQNYsCzXBruiFv7cxTn+/rKokXn8gkaA9AhdcSmuPQ0JtWbiPdgFRHEw==,iv:1y0Mh0p7++vvo6KA1YRhLNxgxYZqOE1fAFl/1qs6uC0=,tag:STWs4Pu4OwB4+fczBFPJpQ==,type:str]
    local:
        path: ENC[AES256_GCM,data:QspoUTPivmAzupIR9FCj4A==,iv:l+YT7qv0VAcwI2sJ7t/QV49x6RQIsIul6LlqKn0BvyA=,tag:24jDdU0JcaxaxwMldmIFlg==,type:str]
regulation:
    max_retries: ENC[AES256_GCM,data:Kw==,iv:aYfPU6qCF03LJflhcqaQfIJjuKIOK1hXcIf8xEh+SUk=,tag:Yi5ZYvnPNXoe0zNnimoejQ==,type:int]
    find_time: ENC[AES256_GCM,data:q9+m,iv:gmHeZ+PeCdymE5vG6PmDE1yP0+ufoPZ6SZy05UG1pgw=,tag:IojuhKyYhWlXzzpYmkPFHQ==,type:int]
    ban_time: ENC[AES256_GCM,data:n0uR,iv:4blCwbaQVmBkNMGVPBsDipgEVNMVxeyl2kr2aod+aJM=,tag:XMK05rqWn567tU4lPIJo0g==,type:int]
log:
    level: ENC[AES256_GCM,data:h7WWzj0=,iv:l5S+e1s6KlUvb0eswlzFswan1YtfqiD7dFnpzcKBdI8=,tag:pPQGM1o01/0r6HT20sDIxQ==,type:str]
telemetry:
    metrics:
        enabled: ENC[AES256_GCM,data:dHPEUi4=,iv:Kp9ueFYAa1PI7BW5pw3UXKX4iK7wuakyVHd6g3Fwhj8=,tag:bDTmExXs5xiPdrlm8UwnoA==,type:bool]
        address: ENC[AES256_GCM,data:YpBVxWbZOlNzbMdOGJfs4V6sPA==,iv:jfJJSOM+fPD7loPSWU+6CnkCIXkKx/EIbVK4x8TU+GU=,tag:S0dQsaYNs69H+1JW9qIOug==,type:str]
        buffers:
            read: ENC[AES256_GCM,data:vc6bEA==,iv:ZsJJPPcl15kgj78/qyzbvo3Qcroauyk8zPE4tzusRmw=,tag:CYqRjDGw/NJiuxv7fb28Tg==,type:int]
            write: ENC[AES256_GCM,data:UXwiQQ==,iv:tJGsOL+Jx77lDrIck3sQe78qnAZ1tqYfoVzaxTw3200=,tag:H3RYinfZKT/Pg+E5DjSSIA==,type:int]
        timeouts:
            read: ENC[AES256_GCM,data:51M=,iv:SbTF0pIQdcVz62dxoWkmUsZb9ROOaUBPNIZg8w52EuQ=,tag:ZfSxVEdb4Tu9Mpuc1DIcsQ==,type:str]
            write: ENC[AES256_GCM,data:YHA=,iv:oEjglTQkYZIqpx3k7He4iCWvbTrZlSGeBdzhNrMlfa0=,tag:64gHX05sA9wnl0PsCuQx8Q==,type:str]
            idle: ENC[AES256_GCM,data:y4fA,iv:f3Ugsy0BtBLmTAHKRn+A6UyOstZLQXP/E/3f82K28mE=,tag:fMlv69J3zVgVBzC2fADepw==,type:str]
webauthn:
    disable: ENC[AES256_GCM,data:XgYprnI=,iv:3DTv/pb1ByGAFe7nKT1GnMJZSQbGRRGTE4q1K54WY5g=,tag:KRnOFJq45EKsFLsyqJKN1w==,type:bool]
    display_name: ENC[AES256_GCM,data:+L4ZAbeUvFY=,iv:JhpbAlKcMalUwRKU2cyMeei32MPASJNtGsNoAKMVw4o=,tag:i6G593EGYa6bDMIoDo4psw==,type:str]
    attestation_conveyance_preference: ENC[AES256_GCM,data:cBdBmIk=,iv:FclKoOqRGEVnjjtuZTTcE3Educ8RYJgIEq+K3+FGibc=,tag:Q6nbvflq++U5EpG/rGLAeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTm5yQW9lY3dRUzdEQzZH
            VWg1Tm10ckxsRHJETmFxYUN1OERVa1V5SFhRCkU5Z3Z6aml5OFpMdUxpVS9KcEFh
            VnlqM0tmdjl3S3ZoZm9YK2hkaU56VlEKLS0tIDNLRTVVSU9MV21pL3c0UHMvZmdT
            MU1ZVmwxL202d2xRTlBITWdwSDdFM28KTCiOOf6VnzKaiW9ljxfPRTCMgbDeWHg7
            UdvZhqMO2ixUjQ4LbKiEt1R9keQ4/JxAdPaG4QbyFSeaFYYqLi4sxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdgfrwphxlpr87qrxd3qqkdrzqufh0tqnzkpak8szkkflh09uf2sjm8llt
    lastmodified: "2026-09-14T09:43:38Z"
    mac: ENC[AES256_GCM,data:c/mV6ftu7MBGI2JAu4XBSf1xa+sWPRN/jqYKIcidrt0+j5Hl26XYc57WlEMHy7u8lec+Sjpb1qdvkoDt5QKwc5lstHwoNK+ZwfRwR7vFnIUsJtVxJ1VIdy2U9K3Bh6NMQaJpCJfp7WNUw/5kd12wVn8MdjrblsU2mFIKqpDVbhc=,iv:LR8CQ9im4TPItXNheUgWNIT9OBloiANFzE4BNy9mRgc=,tag:kDdvSF8nUpjvAkTZ877ulQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
