apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubewall
  namespace: kubewall-system
spec:
  interval: 1h
  chart:
    spec:
      chart: kubewall
      version: ">=0.0.10"
      sourceRef:
        kind: HelmRepository
        name: kubewall
        namespace: kubewall-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
