apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubewall
  namespace: kubewall-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/kubewall
      version: 0.0.0
      sourceRef:
        kind: GitRepository
        name: kubewall
        namespace: kubewall-system
  values:
    replicaCount: 1
    service:
      type: ClusterIP
