apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kubewall
  namespace: kubewall-system
spec:
  interval: 12h
  url: oci://ghcr.io/kubewall/charts/kubewall
  ref:
    semver: ">=0.0.0"
