apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authentik-forwardauth
  namespace: your-namespace
spec:
  forwardAuth:
    address: https://auth.kuipr.de/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
      - X-authentik-username
      - X-authentik-groups
      - X-authentik-email
      - X-authentik-name
      - X-authentik-uid
      - X-authentik-jwt
      - Authorization
      - Set-Cookie
