apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik.yaml: |
    api:
      dashboard: true
    entryPoints:
      web:
        address: ":80"
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
      kubernetesIngress:
        allowExternalNameServices: true
    log:
      level: INFO
