apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 34.4.1
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: traefik
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    deployment:
      replicas: 1
      initContainers:
        - name: volume-permissions
          image: busybox:latest
          command:
            - sh
            - -c
            - touch /data/acme.json; chmod -v 600 /data/acme.json
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
          volumeMounts:
            - mountPath: /data
              name: traefik-data

    podSecurityContext:
      fsGroup: 65532
      fsGroupChangePolicy: "OnRootMismatch"
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true

    service:
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Local

    dashboard:
      enabled: true

    metrics:
      prometheus:
        serviceMonitor:
          enabled: true

    ports:
      web:
        port: 80
        expose:
          default: true
        exposedPort: 80
        protocol: TCP
      traefik:
        port: 9000
        expose:
          default: true
        exposedPort: 9000
        protocol: TCP

    persistence:
      enabled: true
      name: traefik-data
      accessMode: ReadWriteOnce
      size: 5Gi
      path: /data
      storageClass: longhorn

    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: true

    logs:
      general:
        level: INFO

    additionalArguments:
      - --api.dashboard=true
      - --providers.kubernetesIngress=true
      - --providers.kubernetesCRD=true
      - --log.level=INFO
      - --entrypoints.web.address=:80
      - --entrypoints.traefik.address=:9000
