apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 37.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: traefik
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # yaml-language-server: $schema=https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/heads/master/traefik/values.schema.json
    deployment:
      replicas: 1
    podSecurityContext:
      fsGroup: 65532
      fsGroupChangePolicy: "OnRootMismatch"
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true

    ingressRoute:
      dashboard:
        matchRule: Host(`traefik.k8s.kuipr.de`)
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        labels: {}
        entryPoints:
          - websecure
        services:
          - name: api@internal
            kind: TraefikService
        tls:
          secretName: traefik-tls-cert

    service:
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Local

    dashboard:
      enabled: true

    experimental:
      plugins: {}

    metrics:
      addInternals: true
      prometheus:
        buckets: 0.100000, 0.300000, 1.200000, 5.000000
        addEntryPointsLabels: true
        addServicesLabels: true
        addRoutersLabels: true
        serviceMonitor:
          enabled: true

    ports:
      web:
        port: 80
        expose:
          default: true
        exposedPort: 80
        protocol: TCP
      websecure:
        port: 443
        expose:
          default: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: true

    persistence:
      enabled: true
      name: traefik-data
      accessMode: ReadWriteMany
      size: 128Mi
      path: /data
      storageClass: longhorn

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256M

    additionalArguments:
      - --api=true
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.kubernetesIngress=true
      - --providers.kubernetesCRD=true
      - --serverstransport.insecureskipverify=false
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesResolvers.letsencrypt.acme.email=me@dinama.dev
      - --certificatesResolvers.letsencrypt.acme.storage=/data/acme.json
      - --certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=web
      - --certificatesResolvers.letsencrypt.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
    logs:
      general:
        level: "INFO" # @schema enum:[TRACE,DEBUG,INFO,WARN,ERROR,FATAL,PANIC]; default: "INFO"
      access:
        enabled: true
