apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 20.8.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    deployment:
      kind: Deployment
    persistence:
      enabled: true
      storageClass: longhorn
      size: 128M
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
    ports:
      web:
        redirectTo: false
    logs:
      general:
        level: INFO
      access:
        enabled: true
    additionalArguments:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
    volumes:
      - name: traefik-config
        mountPath: /etc/traefik
        type: configMap
        configMap:
          name: traefik-config
          items:
            - key: traefik.yaml
              path: traefik.yaml
