apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "34.5.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    # Global settings
    deployment:
      replicas: 1
    
    # Enable dashboard but remove conflicting labels
    ingressRoute:
      dashboard:
        enabled: true
    
    # Configure ports with proper structure
    ports:
      web:
        port: 80
        exposedPort: 80
        expose: {}
        protocol: TCP
      websecure:
        port: 443
        exposedPort: 443
        expose: {}
        protocol: TCP
    
    # Configure settings for Traefik
    additionalArguments:
      - "--api.dashboard=true"
      - "--certificatesresolvers.letsencrypt.acme.email=daniel.imama02@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--providers.kubernetescrd.allowcrossnamespace=true"
      
    # Service configuration
    service:
      enabled: true
      type: LoadBalancer
      annotations: {}
    
    # Persistent storage for Let's Encrypt certificates
    persistence:
      enabled: true
      storageClass: "longhorn"
      size: 5Gi
    
    # Providers configuration  
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: true
    
    # Resource limits
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"
    
    # Security settings
    securityContext:
      capabilities:
        drop: [ALL]
      readOnlyRootFilesystem: false
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
    
    # Log level
    logs:
      general:
        level: INFO
      access:
        enabled: true
