apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hello-world
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik-forwardauth@Namespace

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hello-world.k8s.kuipr.de`)
      kind: Rule
      services:
        - name: hello-world
          port: 80
