apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hello-world
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hello-world.k8s.kuipr.de`)
      kind: Rule
      services:
      - name: hello-world
        port: 80
      middlewares:
        - name: authentik-forwardauth
          namespace: traefik
