apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-world
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: hello-world
        namespace: flux-system
      dependsOn:
        - name: 1pass-operator
          namespace: 1password
  values:
    replicaCount: 2
    service:
      type: ClusterIP
