# Pi-hole v6 + token-gated DoH — hosted on eclair (public VPS).
#
# DNS topology:
#   Apple device → haproxy :443 (SNI dns.ext.kuipr.de → be_local)
#     → caddy 127.0.0.1:8443 (flake.eclairCaddyVirtualHosts below)
#       → https://127.0.0.1:8053 → dnscrypt-proxy local_doh (TLS shim)
#         → plain://127.0.0.1:53 → Pi-hole container (FTL, ad blocking)
#           → upstreams 1.1.1.1 / 9.9.9.9
#
# The DoH path is gated by a per-device token: caddy only routes
# /<token>/dns-query to dnscrypt-proxy, everything else gets a 403 (which
# is also what gatus probes for). Tokens are 128-bit hex strings from
# secrets/eclair/doh-tokens; device profiles are generated by
# scripts/gen-doh-profiles.
#
# The dashboard rides the sorbet caddy + authelia pattern: sorbet
# reverse-proxies pi.ext.kuipr.de → this container on eclair's tailnet IP.
#
# Verified-against-upstream notes (things that differ from the plan draft):
# - dnscrypt-proxy 2.1.18 static stamps MUST be `sdns://` base64 — the
#   `plain://` URL form is rejected by go-dnsstamps. The stamp below is
#   computed for 127.0.0.1:53 (default port 53 is stripped by the encoder):
#       python3 -c 'import base64,struct; addr=b"127.0.0.1"; \
#         print("sdns://"+base64.urlsafe_b64encode( \
#           b"\x00"+struct.pack("<Q",0)+bytes([len(addr)])+addr).decode())'
#   → sdns://AAAAAAAAAAAACTEyNy4wLjAuMQ
# - dnscrypt-proxy's local_doh always serves TLS (httpServer.ServeTLS
#   fatals without certs), so a self-signed pair is required even though
#   the only client (caddy, same host) skips verification.
# - Pi-hole v6 blocklists are NOT env-configurable (they live in
#   gravity.db, not pihole.toml) — the declarative set is applied via the
#   FTL REST API by pihole-blocklists.service below.
# - Array FTLCONF_* env vars are newline/`;`-separated, NOT JSON.
{lib, ...}: {
  flake = let
    # eclair tailnet IP — also in hosts/eclair/gatus.nix and PLAN.md. Used
    # by sorbet's caddy to reach the dashboard, and to bind the container's
    # web port so it is only reachable inside the tailnet.
    eclairTailscaleIp = "100.99.168.34";

    # Devices owning a DoH token. Adding a device = generate a token in
    # secrets/eclair/doh-tokens (DOH_TOKEN_<UPPER>), list it here, redeploy,
    # then `scripts/gen-doh-profiles <device>` and install the profile.
    dohDevices = ["iphone" "ipad" "macbook"];

    # One Caddyfile route per device: strip the token from the URI (the
    # request keeps its /dns-query path for dnscrypt-proxy's local_doh),
    # tag the access log with the device name (CrowdSec sees it), then
    # forward to the shim over TLS (self-signed; verification skipped —
    # 127.0.0.1 only). `handle` + `uri strip_prefix` rather than
    # `handle_path`: the latter would strip the whole matched path and
    # leave dnscrypt-proxy an empty path to 404 on.
    dohRoutes =
      lib.concatMapStrings (device: ''
        handle /{$DOH_TOKEN_${lib.toUpper device}}/dns-query {
          uri strip_prefix /{$DOH_TOKEN_${lib.toUpper device}}
          log_append device ${device}
          reverse_proxy https://127.0.0.1:8053 {
            transport http {
              tls_insecure_skip_verify
            }
          }
        }
      '')
      dohDevices;
  in {
    # ------------------------------------------------------------------
    # eclair: token-gated DoH vhost (TLS terminated on the VPS itself)
    # ------------------------------------------------------------------
    eclairCaddyVirtualHosts."dns.ext.kuipr.de" = {
      name = "Pi-hole DoH";

      # Machine-to-machine: skip the CrowdSec AppSec engine (WAF) — DNS
      # wire payloads look like probe garbage to it and latency matters.
      appsec.enable = false;

      # The device tokens are secrets in the URL path; caddy's default JSON
      # access logs would leak them to journald (and from there to the
      # CrowdSec agent). Rewrite any 32-hex segment to a placeholder before
      # logging. `format filter` wraps the default json encoder, so the
      # crowdsec caddy parser still gets valid JSON.
      logFormat = ''
        format filter {
          wrap json
          fields {
            request>uri regexp "[0-9a-f]{32}" "TOKEN"
          }
        }
      '';

      extraConfig = ''
        ${dohRoutes}
        # No token → no service. 403 (not 404) is what gatus expects; it
        # also makes probing attempts visible as a distinct status.
        handle {
          error 403
        }
      '';
    };

    # ------------------------------------------------------------------
    # sorbet: Pi-hole dashboard behind authelia, backhauled to eclair
    # ------------------------------------------------------------------
    caddyVirtualHosts."pi.ext.kuipr.de" = {
      name = "Pi-hole";
      extraConfig = ''
        reverse_proxy http://${eclairTailscaleIp}:8090
      '';
      authelia = {
        enable = true;
        # Unauthenticated GET /api/auth answers 401 from FTL itself (no
        # session info beyond `valid: false`), so gatus can probe the full
        # sorbet caddy → tailnet → eclair → pihole path without a bypass
        # returning 200 and without any secret in the probe. Without this
        # bypass authelia 401s the request before it reaches eclair.
        bypassPaths = ["/api/auth"];
      };
    };

    # ------------------------------------------------------------------
    # gatus: probe the token gate (sorbet POV, full public path)
    # ------------------------------------------------------------------
    gatusEndpoints = [
      {
        name = "ext: dns.ext.kuipr.de (DoH gate)";
        group = "external";
        # A tokenless probe must be rejected — this asserts the gate is
        # doing its job, not that DNS resolves. Blocking itself is only
        # verifiable with a valid token (kept off sorbet on purpose).
        url = "https://dns.ext.kuipr.de/dns-query";
        interval = "60s";
        client.timeout = "10s";
        conditions = [
          "[STATUS] == 403"
          "[CERTIFICATE_EXPIRATION] > 168h"
          "[RESPONSE_TIME] < 1500"
        ];
        alerts = [{type = "discord";}];
      }

      {
        name = "Pi-hole dashboard (e2e)";
        group = "external";
        # Unauthenticated → FTL 401 (see bypassPaths above). Failure means
        # the tailnet leg, the container, or FTL is down; authelia being
        # bypassed here means it does NOT cover the SSO path.
        url = "https://pi.ext.kuipr.de/api/auth";
        interval = "60s";
        client.timeout = "10s";
        conditions = [
          "[STATUS] == 401"
          "[RESPONSE_TIME] < 2000"
        ];
        alerts = [{type = "discord";}];
      }
    ];

    # ------------------------------------------------------------------
    # eclair: dnscrypt-proxy + Pi-hole container + convergence units
    # ------------------------------------------------------------------
    eclairNixosModules.piholeDoh = {
      pkgs,
      lib,
      config,
      ...
    }: let
      # Self-signed cert pair for dnscrypt-proxy's local_doh listener. It
      # always serves TLS, and the only client (caddy on the same host)
      # skips verification — the cert exists to satisfy ServeTLS, so a
      # long-lived localhost cert in the (world-readable) store is fine.
      localDohCert = pkgs.runCommand "dnscrypt-local-doh-cert" {} ''
        mkdir -p $out
        ${pkgs.openssl}/bin/openssl req -x509 -newkey rsa:2048 -nodes \
          -keyout $out/localhost.key -out $out/localhost.crt \
          -days 3650 -subj "/CN=localhost" >/dev/null 2>&1
      '';

      # Declarative blocklist set — the source of truth applied by
      # pihole-blocklists.service. Edit here, redeploy, done (gravity
      # refresh is part of the convergence unit).
      blocklists = pkgs.writeText "pihole-blocklists.json" (builtins.toJSON [
        {
          address = "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts";
          comment = "StevenBlack unified hosts (ads + malware)";
        }
        {
          address = "https://big.oisd.nl";
          comment = "OISD big";
        }
      ]);

      # Script: converge gravity.db's list set to the declarative one, then
      # refresh gravity. Runs only when the set's content hash changes.
      applyBlocklists = pkgs.writeShellScript "pihole-apply-blocklists" ''
        set -euo pipefail

        STATE_DIR=/var/lib/pihole
        HASH_FILE="$STATE_DIR/.blocklists.hash"
        NEW_HASH="$(${pkgs.coreutils}/bin/sha256sum ${blocklists} | ${pkgs.coreutils}/bin/cut -d' ' -f1)"

        if [[ -f "$HASH_FILE" && "$(< "$HASH_FILE")" == "$NEW_HASH" ]]; then
          echo "blocklist set unchanged"
          exit 0
        fi

        # Wait for FTL's webserver (container may still be starting).
        for _ in $(${pkgs.coreutils}/bin/seq 1 30); do
          # No -f: any HTTP answer (including 401) means FTL is up.
          if ${pkgs.curl}/bin/curl -s -o /dev/null http://127.0.0.1:8090/api/auth; then
            break
          fi
          sleep 2
        done

        PAYLOAD="$(${pkgs.jq}/bin/jq -n --arg password "$FTLCONF_webserver_api_password" '{password: $password}')"
        RESP="$(${pkgs.curl}/bin/curl -fsS -X POST http://127.0.0.1:8090/api/auth \
          -H 'Content-Type: application/json' -d "$PAYLOAD")"
        SID="$(${pkgs.jq}/bin/jq -r '.session.sid' <<<"$RESP")"
        CSRF="$(${pkgs.jq}/bin/jq -r '.session.csrf' <<<"$RESP")"
        [[ -n "$SID" && "$SID" != "null" ]] || {
          echo "ERROR: Pi-hole API auth failed" >&2
          exit 1
        }
        AUTH=(-H "X-FTL-SID: $SID" -H "X-FTL-CSRF: $CSRF")

        CUR="$(${pkgs.curl}/bin/curl -fsS "''${AUTH[@]}" http://127.0.0.1:8090/api/lists)"

        # Remove block-type lists that are not in the declarative set
        # (UI-added adlists are removed on the next run — allowlists and
        # everything else in the UI are left alone).
        TO_DELETE="$(${pkgs.jq}/bin/jq -c --slurpfile want ${blocklists} '
          [.lists[]
            | select(.type == "block")
            | select(.address as $a | $want[0] | map(.address) | index($a) | not)
            | {item: .address, type: "block"}]' <<<"$CUR")"
        if [[ "$TO_DELETE" != "[]" ]]; then
          ${pkgs.curl}/bin/curl -fsS "''${AUTH[@]}" -X POST http://127.0.0.1:8090/api/lists/batchDelete \
            -H 'Content-Type: application/json' -d "$TO_DELETE" >/dev/null
        fi

        # Add missing declarative lists (POST is idempotent-checked against
        # the set we just fetched — no duplicate-list 400s).
        ${pkgs.jq}/bin/jq -r '.[].address' ${blocklists} | while read -r ADDR; do
          if ! ${pkgs.jq}/bin/jq -e --arg a "$ADDR" \
              '.lists[] | select(.type == "block" and .address == $a)' <<<"$CUR" >/dev/null; then
            COMMENT="$(${pkgs.jq}/bin/jq -r --arg a "$ADDR" \
              '[.[] | select(.address == $a)][0].comment' ${blocklists})"
            ${pkgs.curl}/bin/curl -fsS "''${AUTH[@]}" -X POST 'http://127.0.0.1:8090/api/lists?type=block' \
              -H 'Content-Type: application/json' \
              -d "$(${pkgs.jq}/bin/jq -n --arg a "$ADDR" --arg c "$COMMENT" \
                '{address: $a, comment: $c}')" >/dev/null
          fi
        done

        echo "$NEW_HASH" > "$HASH_FILE"

        # Pull the (possibly new) lists into the blocking table now instead
        # of waiting for the weekly gravity timer.
        ${pkgs.podman}/bin/podman exec pihole pihole -g
      '';
    in {
      sops.secrets = {
        # Caddy expands {$DOH_TOKEN_*} from this file at config load.
        "doh-tokens" = {
          sopsFile = ../secrets/eclair/doh-tokens;
          format = "dotenv";
          key = "";
          owner = "root";
        };

        # FTLCONF_webserver_api_password — plaintext, because the same
        # secret is needed to log into the REST API for the blocklist
        # bootstrap (webserver.api.pwhash is write-only inside FTL).
        "doh-env" = {
          sopsFile = ../secrets/eclair/doh-env;
          format = "dotenv";
          key = "";
          owner = "root";
        };
      };

      # Feed the tokens to caddy as a second EnvironmentFile (the first is
      # the AppSec key — see services/eclair-caddy.nix), order the
      # container after tailscaled (the dashboard publish binds the
      # tailnet IP, which only exists once tailscaled is up), and declare
      # the convergence units.
      systemd = {
        services = {
          caddy.serviceConfig.EnvironmentFile = [
            config.sops.secrets."doh-tokens".path
          ];

          "podman-pihole" = {
            after = ["tailscaled.service"];
            wants = ["tailscaled.service"];
          };

          # Converge the declarative blocklist set into gravity.db, then
          # refresh. Runs on boot (covers image pulls on a fresh host) and
          # whenever the set's hash changes.
          pihole-blocklists = {
            description = "Pi-hole declarative blocklist convergence";
            wantedBy = ["multi-user.target"];
            after = ["podman-pihole.service"];
            requires = ["podman-pihole.service"];
            # FTLCONF_webserver_api_password (see doh-env above) — the
            # script uses it to log into the REST API.
            serviceConfig = {
              Type = "oneshot";
              ExecStart = applyBlocklists;
              RemainAfterExit = true;
              EnvironmentFile = [config.sops.secrets."doh-env".path];
            };
          };

          # Weekly gravity refresh so upstream list content (not just the
          # list set) stays fresh. Runs inside the container, so no
          # curl/auth needed.
          pihole-gravity = {
            description = "Pi-hole gravity update";
            after = ["podman-pihole.service"];
            requires = ["podman-pihole.service"];
            serviceConfig = {
              Type = "oneshot";
              ExecStart = "${pkgs.podman}/bin/podman exec pihole pihole -g";
            };
            startAt = "Sun 03:00";
          };
        };

        tmpfiles.rules = [
          "d /var/lib/pihole 0700 root root -"
        ];
      };

      # dnscrypt-proxy as a pure DoH shim: no plain listener, no public
      # resolver list — exactly one static server (the local Pi-hole).
      services.dnscrypt-proxy = {
        enable = true;
        # The upstream example config would re-add public resolver sources;
        # we want ONLY the static pihole-local server.
        upstreamDefaults = false;
        settings = {
          # No plain-DNS listener: caddy talks local_doh, everything DNS on
          # the host goes through Pi-hole (see networking.nameservers).
          listen_addresses = [];
          server_names = ["pihole-local"];
          static."pihole-local".stamp = "sdns://AAAAAAAAAAAACTEyNy4wLjAuMQ";
          cache = true;

          # The DoH shim. Requires TLS certs even for loopback-only use —
          # self-signed pair above, caddy skips verification.
          local_doh = {
            listen_addresses = ["127.0.0.1:8053"];
            path = "/dns-query";
            cert_file = "${localDohCert}/localhost.crt";
            cert_key_file = "${localDohCert}/localhost.key";
          };

          # dnscrypt-proxy's own blocking/cloaking: off — filtering is
          # Pi-hole's job (single source of truth in gravity.db).
        };
      };

      # Keep the box's own resolver independent of the Pi-hole stack: a
      # plain resolv.conf pointing at 127.0.0.1 would deadlock at first
      # boot (podman image pull needs DNS, the podman DNS path needs
      # dnscrypt → needs the pihole image). Use the provider's resolvers
      # (eclair's current DHCP resolv.conf anyway). mkOverride 50 to beat
      # the dnscrypt-proxy module's mkDefault [127.0.0.1].
      networking.nameservers = lib.mkOverride 50 ["46.38.225.230" "46.38.252.230"];

      virtualisation = {
        podman.enable = true;
        oci-containers.backend = "podman";
        oci-containers.containers.pihole = {
          image = "docker.io/pihole/pihole:2025.11.1@sha256:848cf5af61397e6976e2fc356aa00aaa3d3a53b2ac90a956675779ff1f4bdf34";
          autoStart = true;
          environmentFiles = [config.sops.secrets."doh-env".path];
          environment = {
            TZ = "Europe/Berlin";

            # Upstream resolvers (newline-separated arrays, not JSON).
            FTLCONF_dns_upstreams = "1.1.1.1;9.9.9.9";

            # ALL: the published-port path forwards to the container's eth0,
            # "local-only" listening mode refuses. Required for 127.0.0.1:53.
            FTLCONF_dns_listeningMode = "ALL";

            # LAN names so DoH clients can resolve hosts at home.
            FTLCONF_dns_hosts = "192.168.0.85 sorbet;192.168.0.5 tiramisu";

            # Split horizon: *.int.kuipr.de (and the domain itself) answer
            # with sorbet from anywhere, like dnsmasq does on the LAN.
            FTLCONF_misc_dnsmasq_lines = "address=/int.kuipr.de/192.168.0.85";
          };
          volumes = [
            "/var/lib/pihole:/etc/pihole:rw"
          ];
          ports = [
            # DNS for dnscrypt-proxy (loopback only).
            "127.0.0.1:53:53/tcp"
            "127.0.0.1:53:53/udp"
            # Dashboard: loopback (for pihole-blocklists.service — no
            # dependency on the tailnet IP existing yet) plus the tailnet
            # IP so only sorbet's caddy (pi.ext.kuipr.de → authelia) can
            # reach it.
            "127.0.0.1:8090:8080/tcp"
            "${eclairTailscaleIp}:8090:8080/tcp"
          ];
          # Podman does not inherit image HEALTHCHECKs — mirror the
          # upstream one (dig pi.hole, no recursion needed).
          # Unhealthy → podman kills the container; systemd's Restart
          # recreates it (same pattern as subtidal).
          extraOptions = [
            "--health-cmd=dig -p 53 +short +norecurse +retry=0 @127.0.0.1 pi.hole >/dev/null"
            "--health-interval=60s"
            "--health-on-failure=kill"
            "--health-retries=3"
            "--health-start-period=30s"
            "--health-timeout=15s"
          ];
        };
      };

      # Tailnet traffic lands on tailscale0, which the firewall drops by
      # default — allow only the dashboard port there (8053/53 stay
      # loopback-only and never cross the wire).
      networking.firewall.interfaces.tailscale0.allowedTCPPorts = [8090];
    };
  };
}
