# Pi-hole v6 + token-gated DoH — hosted on eclair (public VPS).
#
# DNS topology:
#   Apple device → haproxy :443 (SNI dns.ext.kuipr.de → be_local)
#     → caddy 127.0.0.1:8443 (flake.eclairCaddyVirtualHosts below)
#       → https://127.0.0.1:8053 → dnsproxy (DoH shim, TLS)
#         → plain://127.0.0.1:53 → Pi-hole container (FTL, ad blocking)
#           → upstreams 1.1.1.1 / 9.9.9.9
#
# The DoH path is gated by a per-device token: caddy only routes
# /<token>/dns-query to dnsproxy, everything else gets a 403 (which is
# also what gatus probes for). Tokens are 128-bit hex strings from
# secrets/eclair/doh-tokens; device profiles are generated by
# scripts/gen-doh-profiles.
#
# The dashboard rides the sorbet caddy + authelia pattern: sorbet
# reverse-proxies pi.ext.kuipr.de → this container on eclair's tailnet
# IP. FTL's own webserver password is cleared (FTLCONF_webserver_api_
# password = "") — authelia is the only gate; the open REST API is what
# pihole-blocklists.service talks to.
#
# Verified-against-upstream notes (things that differ from the plan draft):
# - dnscrypt-proxy CANNOT shim for a plain-DNS upstream: 2.1.18 rejects
#   plain servers outright ("Unsupported protocol for [pihole-local]:
#   [Plain]") and waits forever. dnsproxy (AdGuard) speaks DoH on one
#   side and plain UDP/TCP on the other — that's the shim used below.
# - Pi-hole v6 blocklists are NOT env-configurable (they live in
#   gravity.db, not pihole.toml) — the declarative set is applied via the
#   FTL REST API by pihole-blocklists.service below.
# - Array FTLCONF_* env vars are newline/`;`-separated, NOT JSON.
{lib, ...}: {
  flake = let
    # eclair tailnet IP — also in hosts/eclair/gatus.nix and PLAN.md. Used
    # by sorbet's caddy to reach the dashboard, and to bind the container's
    # web port so it is only reachable inside the tailnet.
    eclairTailscaleIp = "100.99.168.34";

    # Devices owning a DoH token. Adding a device = generate a token in
    # secrets/eclair/doh-tokens (DOH_TOKEN_<UPPER>), list it here, redeploy,
    # then `scripts/gen-doh-profiles <device>` and install the profile.
    dohDevices = [
      "iphone"
      "ipad"
      "macbook"
    ];

    # One Caddyfile route per device: strip the token from the URI (the
    # request keeps its /dns-query path for dnsproxy's DoH listener),
    # tag the access log with the device name (CrowdSec sees it), then
    # forward to the shim over TLS (self-signed; verification skipped —
    # 127.0.0.1 only). `handle` + `uri strip_prefix` rather than
    # `handle_path`: the latter would strip the whole matched path and
    # leave dnsproxy an empty path to 404 on.
    dohRoutes =
      lib.concatMapStrings (device: ''
        handle /{$DOH_TOKEN_${lib.toUpper device}}/dns-query {
          uri strip_prefix /{$DOH_TOKEN_${lib.toUpper device}}
          log_append device ${device}
          reverse_proxy https://127.0.0.1:8053 {
            transport http {
              tls_insecure_skip_verify
            }
          }
        }
      '')
      dohDevices;
  in {
    # ------------------------------------------------------------------
    # eclair: token-gated DoH vhost (TLS terminated on the VPS itself)
    # ------------------------------------------------------------------
    eclairCaddyVirtualHosts."dns.ext.kuipr.de" = {
      name = "Pi-hole DoH";

      # Machine-to-machine: skip the CrowdSec AppSec engine (WAF) — DNS
      # wire payloads look like probe garbage to it and latency matters.
      appsec.enable = false;

      # The device tokens are secrets in the URL path; caddy's default JSON
      # access logs would leak them to journald (and from there to the
      # CrowdSec agent). Rewrite any 32-hex segment to a placeholder before
      # logging. `format filter` wraps the default json encoder, so the
      # crowdsec caddy parser still gets valid JSON.
      logFormat = ''
        format filter {
          wrap json
          fields {
            request>uri regexp "[0-9a-f]{32}" "TOKEN"
          }
        }
      '';

      extraConfig = ''
        ${dohRoutes}
        # No token → no service. 403 (not 404) is what gatus expects; it
        # also makes probing attempts visible as a distinct status.
        handle {
          error 403
        }
      '';
    };

    # ------------------------------------------------------------------
    # sorbet: Pi-hole dashboard behind authelia, backhauled to eclair
    # ------------------------------------------------------------------
    caddyVirtualHosts."pi.ext.kuipr.de" = {
      name = "Pi-hole";
      extraConfig = ''
        reverse_proxy http://${eclairTailscaleIp}:8090
      '';
      authelia = {
        enable = true;
        # Passwordless FTL answers GET /api/auth with
        # {"session":{"valid":true,...,"message":"no password set"}}
        # (200), so gatus can probe the full sorbet caddy → tailnet →
        # eclair → pihole path without a secret in the probe. Without
        # this bypass authelia would 302 the request before it reaches
        # eclair.
        bypassPaths = ["/api/auth"];
      };
    };

    # ------------------------------------------------------------------
    # gatus: probe the token gate (sorbet POV, full public path)
    # ------------------------------------------------------------------
    gatusEndpoints = [
      {
        name = "ext: dns.ext.kuipr.de (DoH gate)";
        group = "external";
        # A tokenless probe must be rejected — this asserts the gate is
        # doing its job, not that DNS resolves. Blocking itself is only
        # verifiable with a valid token (kept off sorbet on purpose).
        url = "https://dns.ext.kuipr.de/dns-query";
        interval = "60s";
        client.timeout = "10s";
        conditions = [
          "[STATUS] == 403"
          "[CERTIFICATE_EXPIRATION] > 168h"
          "[RESPONSE_TIME] < 1500"
        ];
        alerts = [{type = "discord";}];
      }

      {
        name = "Pi-hole dashboard (e2e)";
        group = "external";
        # Passwordless FTL answers 200 (see bypassPaths above). Failure
        # means the tailnet leg, the container, or FTL is down; authelia
        # being bypassed here means it does NOT cover the SSO path.
        url = "https://pi.ext.kuipr.de/api/auth";
        interval = "60s";
        client.timeout = "10s";
        conditions = [
          "[STATUS] == 200"
          "[RESPONSE_TIME] < 2000"
        ];
        alerts = [{type = "discord";}];
      }
    ];

    # ------------------------------------------------------------------
    # eclair: dnsproxy DoH shim + Pi-hole container + convergence units
    # ------------------------------------------------------------------
    eclairNixosModules.piholeDoh = {
      pkgs,
      lib,
      config,
      ...
    }: let
      # Self-signed cert pair for dnsproxy's DoH listener. The only
      # client (caddy on the same host) skips verification — the cert
      # exists so the shim can serve TLS on the loopback at all, so a
      # long-lived localhost cert in the (world-readable) store is fine.
      localDohCert = pkgs.runCommand "doh-local-cert" {} ''
        mkdir -p $out
        ${pkgs.openssl}/bin/openssl req -x509 -newkey rsa:2048 -nodes \
          -keyout $out/localhost.key -out $out/localhost.crt \
          -days 3650 -subj "/CN=localhost" >/dev/null 2>&1
      '';

      # Declarative blocklist set — the source of truth applied by
      # pihole-blocklists.service. Edit here, redeploy, done (gravity
      # refresh is part of the convergence unit).
      blocklists = pkgs.writeText "pihole-blocklists.json" (
        builtins.toJSON [
          {
            address = "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts";
            comment = "StevenBlack unified hosts (ads + malware)";
          }
          {
            address = "https://big.oisd.nl";
            comment = "OISD big";
          }
          {
            address = "https://media.githubusercontent.com/media/zachlagden/Pi-hole-Optimized-Blocklists/main/lists/all_domains.txt";
            comment = "Zach Lagden's optimized blocklist";
          }
        ]
      );

      # Script: converge gravity.db's list set to the declarative one, then
      # refresh gravity. Runs only when the set's content hash changes.
      applyBlocklists = pkgs.writeShellScript "pihole-apply-blocklists" ''
        set -euo pipefail

        STATE_DIR=/var/lib/pihole
        HASH_FILE="$STATE_DIR/.blocklists.hash"
        NEW_HASH="$(${pkgs.coreutils}/bin/sha256sum ${blocklists} | ${pkgs.coreutils}/bin/cut -d' ' -f1)"

        if [[ -f "$HASH_FILE" && "$(< "$HASH_FILE")" == "$NEW_HASH" ]]; then
          echo "blocklist set unchanged"
          exit 0
        fi

        # Wait for FTL's webserver (container may still be starting).
        for _ in $(${pkgs.coreutils}/bin/seq 1 30); do
          # No -f: any HTTP answer (even an error) means FTL is up.
          if ${pkgs.curl}/bin/curl -s -o /dev/null http://127.0.0.1:8090/api/auth; then
            break
          fi
          sleep 2
        done

        # No auth: the webserver password is deliberately cleared (see
        # FTLCONF_webserver_api_password below) — the dashboard and API
        # are gated by authelia on sorbet, and with no password set FTL
        # serves everything unauthenticated (verified: POST /api/lists
        # returns 201 without any SID/CSRF headers).
        CUR="$(${pkgs.curl}/bin/curl -fsS http://127.0.0.1:8090/api/lists)"

        # Remove block-type lists that are not in the declarative set
        # (UI-added adlists are removed on the next run — allowlists and
        # everything else in the UI are left alone).
        TO_DELETE="$(${pkgs.jq}/bin/jq -c --slurpfile want ${blocklists} '
          [.lists[]
            | select(.type == "block")
            | select(.address as $a | $want[0] | map(.address) | index($a) | not)
            | {item: .address, type: "block"}]' <<<"$CUR")"
        if [[ "$TO_DELETE" != "[]" ]]; then
          ${pkgs.curl}/bin/curl -fsS -X POST http://127.0.0.1:8090/api/lists/batchDelete \
            -H 'Content-Type: application/json' -d "$TO_DELETE" >/dev/null
        fi

        # Add missing declarative lists (POST is idempotent-checked against
        # the set we just fetched — no duplicate-list 400s).
        ${pkgs.jq}/bin/jq -r '.[].address' ${blocklists} | while read -r ADDR; do
          if ! ${pkgs.jq}/bin/jq -e --arg a "$ADDR" \
              '.lists[] | select(.type == "block" and .address == $a)' <<<"$CUR" >/dev/null; then
            COMMENT="$(${pkgs.jq}/bin/jq -r --arg a "$ADDR" \
              '[.[] | select(.address == $a)][0].comment' ${blocklists})"
            ${pkgs.curl}/bin/curl -fsS -X POST 'http://127.0.0.1:8090/api/lists?type=block' \
              -H 'Content-Type: application/json' \
              -d "$(${pkgs.jq}/bin/jq -n --arg a "$ADDR" --arg c "$COMMENT" \
                '{address: $a, comment: $c}')" >/dev/null
          fi
        done

        echo "$NEW_HASH" > "$HASH_FILE"

        # Pull the (possibly new) lists into the blocking table now instead
        # of waiting for the weekly gravity timer.
        ${pkgs.podman}/bin/podman exec pihole pihole -g
      '';
    in {
      sops.secrets = {
        # Caddy expands {$DOH_TOKEN_*} from this file at config load.
        "doh-tokens" = {
          sopsFile = ../secrets/eclair/doh-tokens;
          format = "dotenv";
          key = "";
          owner = "root";
        };
      };

      # Feed the tokens to caddy as a second EnvironmentFile (the first is
      # the AppSec key — see services/eclair-caddy.nix), order the
      # container after tailscaled (the dashboard publish binds the
      # tailnet IP, which only exists once tailscaled is up), and declare
      # the convergence units.
      systemd = {
        services = {
          caddy.serviceConfig.EnvironmentFile = [
            config.sops.secrets."doh-tokens".path
          ];

          "podman-pihole" = {
            after = ["tailscaled.service"];
            wants = ["tailscaled.service"];
          };

          # Converge the declarative blocklist set into gravity.db, then
          # refresh. Runs on boot (covers image pulls on a fresh host) and
          # whenever the set's hash changes.
          pihole-blocklists = {
            description = "Pi-hole declarative blocklist convergence";
            wantedBy = ["multi-user.target"];
            after = ["podman-pihole.service"];
            requires = ["podman-pihole.service"];
            # The REST API is open (no webserver password — see the
            # container env below), so the script needs no credentials.
            serviceConfig = {
              Type = "oneshot";
              ExecStart = applyBlocklists;
              RemainAfterExit = true;
            };
          };

          # Weekly gravity refresh so upstream list content (not just the
          # list set) stays fresh. Runs inside the container, so no
          # curl/auth needed.
          pihole-gravity = {
            description = "Pi-hole gravity update";
            after = ["podman-pihole.service"];
            requires = ["podman-pihole.service"];
            serviceConfig = {
              Type = "oneshot";
              ExecStart = "${pkgs.podman}/bin/podman exec pihole pihole -g";
            };
            startAt = "Sun 03:00";
          };
        };

        tmpfiles.rules = [
          "d /var/lib/pihole 0700 root root -"
        ];
      };

      # dnsproxy as a pure DoH shim: binds only the loopback, serves
      # RFC 8484 GET/POST at /dns-query, forwards everything to the local
      # Pi-hole. dnscrypt-proxy was tried first but refuses plain-DNS
      # upstreams outright ("Unsupported protocol for [pihole-local]:
      # [Plain]") — dnsproxy exists precisely for this shape.
      systemd.services.dnsproxy-doh = {
        description = "DoH shim in front of the Pi-hole container";
        wantedBy = ["multi-user.target"];
        # Soft dependency: when the container is down the shim keeps
        # answering (with SERVFAIL), so pihole restarts don't cascade.
        wants = ["podman-pihole.service"];
        serviceConfig = {
          ExecStart =
            "${pkgs.dnsproxy}/bin/dnsproxy "
            + "--listen=127.0.0.1 "
            # --port=0 disables the plain TCP/UDP listener: the default
            # port 53 would collide with the container's published 53.
            + "--port=0 "
            + "--https-port=8053 "
            + "--tls-crt=${localDohCert}/localhost.crt "
            + "--tls-key=${localDohCert}/localhost.key "
            + "--upstream=127.0.0.1:53";
          Restart = "on-failure";
          RestartSec = 5;
          # No new privileges + private tmp; nothing to write anywhere.
          NoNewPrivileges = true;
          ProtectSystem = "strict";
          ProtectHome = true;
        };
      };

      # Keep the box's own resolver independent of the Pi-hole stack: a
      # plain resolv.conf pointing at 127.0.0.1 would deadlock at first
      # boot (podman image pull needs DNS, the podman DNS path needs
      # the pihole image). Use the provider's resolvers (eclair's current
      # DHCP resolv.conf anyway).
      networking.nameservers = lib.mkOverride 50 [
        "46.38.225.230"
        "46.38.252.230"
      ];

      virtualisation = {
        podman.enable = true;
        oci-containers.backend = "podman";
        oci-containers.containers.pihole = {
          image = "docker.io/pihole/pihole:2026.09.0@sha256:bd3fc82ee1b1473a45fc074379dcd9fd7ce3e933809c44e10c0df9b22fd5de63";
          autoStart = true;
          environment = {
            TZ = "Europe/Berlin";

            # Deliberate empty password → no FTL login/API auth. The
            # docker image ships a default password hash in its baked-in
            # pihole.toml, so this empty value is load-bearing: it clears
            # webserver.api.password. The dashboard is gated by authelia
            # on sorbet instead, and the blocklist script relies on the
            # open API (verified: POST /api/lists → 201 with no SID).
            # Note: with the env var set, `pihole-FTL --config
            # webserver.api.password` is read-only — the password can
            # only be changed here, not via pihole -a -p.
            FTLCONF_webserver_api_password = "";

            # Upstream resolvers (newline-separated arrays, not JSON).
            FTLCONF_dns_upstreams = "1.1.1.1;9.9.9.9";

            # ALL: the published-port path forwards to the container's eth0,
            # "local-only" listening mode refuses. Required for 127.0.0.1:53.
            FTLCONF_dns_listeningMode = "ALL";

            # Names for every client that can reach FTL, so the dashboard
            # shows hosts instead of bare addresses. sorbet's podman
            # containers query host dnsmasq directly (--dns=192.168.0.85,
            # pinned IPs); dnsmasq forwards with ECS, but traffic addressed
            # to the host's own LAN address gets rewritten to 192.168.0.85
            # on the way in, so container DNS shares the "sorbet" client —
            # except raw-socket resolvers (gatus's dns:// probe), which
            # keep their pinned container IP. 10.88.0.1 is eclair's own
            # published-port path: DoH devices all arrive through it and
            # cannot be told apart (inherent to DoH).
            FTLCONF_dns_hosts = "192.168.0.85 sorbet;192.168.0.5 tiramisu;10.88.3.21 multi-scrobbler;10.88.3.22 koito;10.88.3.23 last-fm-presence;10.88.3.24 gatus;10.89.2.20 authelia;10.89.0.20 gluetun;100.120.32.9 sorbet-ts;100.68.101.35 macbook;10.88.0.1 doh-clients";

            # Split horizon: *.int.kuipr.de (and the domain itself) answer
            # with sorbet from anywhere. This is the single wildcard
            # authority now — sorbet's dnsmasq no longer answers .int
            # locally and forwards here instead.
            FTLCONF_misc_dnsmasq_lines = "address=/int.kuipr.de/192.168.0.85";
          };
          volumes = [
            "/var/lib/pihole:/etc/pihole:rw"
          ];
          ports = [
            # DNS for the DoH shim (loopback) plus the tailnet IP: the
            # upstream for sorbet's LAN dnsmasq (dnsDhcp module), which
            # forwards unresolved LAN names here over tailscale0.
            "127.0.0.1:53:53/tcp"
            "127.0.0.1:53:53/udp"
            "${eclairTailscaleIp}:53:53/tcp"
            "${eclairTailscaleIp}:53:53/udp"
            # Dashboard: loopback (for pihole-blocklists.service — no
            # dependency on the tailnet IP existing yet) plus the tailnet
            # IP so only sorbet's caddy (pi.ext.kuipr.de → authelia) can
            # reach it. Target port 80: FTL's default webserver port
            # (verified: `pihole-FTL --config webserver.port` → 80/443).
            "127.0.0.1:8090:80/tcp"
            "${eclairTailscaleIp}:8090:80/tcp"
          ];
          # Podman does not inherit image HEALTHCHECKs — mirror the
          # upstream one (dig pi.hole, no recursion needed). The command
          # must ride out FTL's own startup: podman runs healthchecks as
          # transient systemd units (subtidal pattern), and deploy-rs
          # aborts activation on ANY failed unit — so the first tick,
          # which fires while FTL is still booting, retries a few times
          # before reporting failure. Unhealthy → podman kills the
          # container; systemd's Restart recreates it (same as subtidal).
          extraOptions = [
            "--health-cmd=dig -p 53 +short +norecurse +retry=0 @127.0.0.1 pi.hole >/dev/null || { for _ in 1 2 3; do sleep 3; dig -p 53 +short +norecurse +retry=0 @127.0.0.1 pi.hole >/dev/null && exit 0; done; exit 1; }"
            "--health-interval=60s"
            "--health-on-failure=kill"
            "--health-retries=3"
            "--health-start-period=30s"
            "--health-timeout=15s"
            # podman injects "10.88.0.1 host.containers.internal" into the
            # container's /etc/hosts, which beats FTLCONF_dns_hosts in FTL's
            # reverse lookup — the published-port client would stay named
            # host.containers.internal. --no-hosts drops podman's entries;
            # FTL then names the client from FTLCONF_dns_hosts (doh-clients).
            # The healthcheck and FTL only use numeric addresses, so nothing
            # inside the container needs name resolution.
            "--no-hosts"
          ];
        };
      };

      # Tailnet traffic lands on tailscale0, which the firewall drops by
      # default — allow the dashboard port (8090, sorbet's caddy →
      # authelia'd pi.ext) and the LAN-dnsmasq upstream port (53, from
      # sorbet's dnsmasq). 8053 stays loopback-only and never crosses
      # the wire.
      networking.firewall.interfaces.tailscale0 = {
        allowedTCPPorts = [
          53
          8090
        ];
        allowedUDPPorts = [53];
      };
    };
  };
}
