apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-tls
  namespace: traefik
spec:
  secretName: traefik-tls-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: traefik.k8s.kuipr.de
  dnsNames:
  - traefik.k8s.kuipr.de
