apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/hl-sol-c1/infrastructure/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: metallb-system
  wait: true
