data: ENC[AES256_GCM,data:gduW5ePmggHxVwMO+kc8ZC1kykDVZP2/cG0p49KqhWaK9TGwmVRsRjmp4pk5jNXMg9ONbCQECr1EMSASuCZa/APxoLKIM/VQ/+N6Ci5+FyhzF3NXie6dz+sM6bso739+E15yLHzSy32dqU/wN2BY/wsxpA+iQyQsO/yqAwb7iY8b82je6L6o7I1yxRTNqkBbvT+wPMfHyCuaNyOGvK8d3xKj0RSlVXNOmOflIhvlb+PqK7Ff7Zn1hHFxrjKvqdWwZOI0afqZQPLfCNybC5HiggTav0C/B9ruEVPm3ccjY828eNqRuFNloujG49GmtZZEgrQSDae6Yi7RIVbII6Baj7xwP/YqCieEWVNovVRJKS/mwe5YAxPzlPM+dYxyqrboa9edRbwynWyIxNwBmqddajtT15DwEXHSIyFt3RnUOt6Z2CovRdeELXwitN+rjrDp8WJBNpvezgofFAgs1iJhUCrzw8TuUd9hvboilM0kD56dBdc4re3E7Y+WNro99yTwHYMINTbra6mYbNkyp9XgA7qplyupv0F/LqVsv2KUeTXeqcozoD/qkAaMqiMNp9FyFPqIT2qxZbT6l7IWaRyFEZhs4btzQVWkG2nJl51OZSoFCUubX4YF4A6Lp2A1YlcnwbwH4tkkDdssiKmSu0pDywilaI1xi2byq1PpEZpW6v8UQGEMbeRAwC2qQJMxdZpmXhMsaIWPLlIhxwJVTqvR/NCUSpSajtEviZalAd2udYmRTQJP2f9yJ46EZRPAwR9NL45pisRNdt2oedUgSalriyNsuE1li9LWffJZ6CBS717Yj9Vm+rn0jALD35NB8dco2cFbuTeUC5jUtij06TuTRWft+YdrO6+WDRLlVQ0tLlAfbC3TQWSA2tgJ7lH+dtOX+UAaSnt44ItNXXCr7JZ6XJAttZNSkg+JCKQpK3jgZQ==,iv:SCjNgzzRkFjTX0mV27AavmZYGgN8JkYUzh2qvpMNAbo=,tag:T0ItVn9GZSW8xKT0/tMjsg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeXR6aS9TVVN5MklDNHMz
            QjhVOE1aNXU4T0VtQ0hNdXFnMEVzdFA4WkhVClNiVjNUN1kyN09FbTlSczhBVi9D
            T2VnOU03SXNKaUNZMHdEN21UTi9Hb1EKLS0tIFJCZkNhMzdQa3VPVUk2dXIvbEtM
            TjQyWWhTdWRkb3B2ck1GaGd5TTE3U0kKWWQYYOI5NKg2ZbImrs/ZlVubVdR+PBGu
            RzBczC7Di556tlnbnXCuL8eZAgieuyRiwU8OYlL1hyzWnU/yiI8lbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pdgfrwphxlpr87qrxd3qqkdrzqufh0tqnzkpak8szkkflh09uf2sjm8llt
    lastmodified: "2026-10-08T06:40:48Z"
    mac: ENC[AES256_GCM,data:D0G09uTtX1afAIivBMBDCUUMH8Z6QPe5rv4oDc+dtnU+i8rW3xoKU3a4LSekT5l2XeZpOWkLBc61ZUL49oVd5Iy0awcaeebWlPuTMC29t2u1WqV+lVFTktaOWEB64wAjckxm48fJwtaXIOKPUIMEk5ejVZNcphlDRxn+pvuOUxQ=,iv:Dhk4iS+388P/y99z1COfSdT/JA5nvnghSDlKA6u49sI=,tag:+uFac1ALky/fka4cs9C1MA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
