---
extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 120
    level: warning

  # accept both     key:
  #                   - item
  # and
  #                 key:
  #                 - item
  indentation:
    spaces: 2
    indent-sequences: consistent

  # don't require document start marker ---
  document-start: disable

  # don't warn if truthy values used are not quoted
  truthy: disable
  
  # allow comments to start without a space
  comments:
    require-starting-space: false

  # be a bit more lenient on syntax
  comments-indentation: disable
  
  # allow empty lines with whitespace
  empty-lines:
    max: 2
    max-start: 2
    max-end: 2
    
  # gotk-components.yaml is very large, let's be more lenient with it
  # this can be ignored directly via special comments in the file if needed
  new-line-at-end-of-file: disable
