apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: "0.13.11"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    # Define controller and speaker configurations as needed
    speaker:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
