apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "34.4.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    # Global settings
    deployment:
      replicas: 1
    
    # Enable dashboard
    ingressRoute:
      dashboard:
        enabled: true
        # Secure the dashboard with basic auth
        annotations:
          kubernetes.io/ingress.class: traefik
        labels:
          app.kubernetes.io/name: traefik-dashboard
    
    # Configure ports
    ports:
      web:
        port: 80
        exposedPort: 80
        expose: true
        protocol: TCP
      websecure:
        port: 443
        exposedPort: 443
        expose: true
        protocol: TCP
    
    # Configure settings for Traefik
    additionalArguments:
      - "--api.dashboard=true"
      - "--certificatesresolvers.letsencrypt.acme.email=your-email@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--providers.kubernetescrd.allowcrossnamespace=true"
      # Comment out automatic redirection to allow HTTP access during initial setup
      # - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      
    # Service configuration
    service:
      enabled: true
      type: LoadBalancer
      # If you have MetalLB or similar, you can specify the load balancer IP
      # loadBalancerIP: "192.168.1.100"
      annotations:
        # Add annotations for your specific environment if needed
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    
    # Persistent storage for Let's Encrypt certificates
    persistence:
      enabled: true
      storageClass: "longhorn"
      size: 5Gi
    
    # Providers configuration  
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: true
    
    # Resource limits
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
      limits:
        cpu: "300m"
        memory: "150Mi"
    
    # Security settings
    securityContext:
      capabilities:
        drop: [ALL]
      readOnlyRootFilesystem: true
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532
    
    # Log level
    logs:
      general:
        level: INFO
      access:
        enabled: true
