apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hello-world
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/KuiprLab/hello-world-app.git
  ref:
    branch: main
