apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-deployments
  namespace: flux-system
spec:
  interval: 10m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra-deploy/dev
  dependsOn:
    - name: flux-system
    - name: infrastructure
