apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1pass-operator
  namespace: 1password
spec:
  interval: 1h
  chart:
    spec:
      chart: connect
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: connect-helm-charts
        namespace: 1password
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    connect:
      credentialsName: 1pass-connect
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532 
        runAsGroup: 65532
        capabilities:
         drop: ["ALL"]
        seccompProfile:
         type: "RuntimeDefault"
    operator:
      create: true
      pollingInterval: 300
      autoRestart: true
      token:
        key: token
        name: 1pass-operator
      hpa:
        enabled: true
        maxReplicas: 3
